service: dynamodb

provider:
  name: aws
  profile: ${opt:profile, "nadtakan"}
  region: ${opt:region, "us-east-1"}

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books-${self:provider.stage}-${self:provider.region}
        AttributeDefinitions:
          - AttributeName: ISBN
            AttributeType: S
        KeySchema:
          - AttributeName: ISBN
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
